name: Deploy React App to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      working-directory: ./collaborative-canvas/frontend
      run: npm install

    - name: Build React app
      working-directory: ./collaborative-canvas/frontend
      run: npm run build

    - name: Assume Role and Export Credentials
      id: assume-role
      run: |
        CREDS=$(aws sts assume-role \
          --role-arn ${{ secrets.AWS_ROLE_ARN }} \
          --role-session-name github-actions-session)
        
        echo "AWS_ACCESS_KEY_ID=$(echo $CREDS | jq -r .Credentials.AccessKeyId)" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=$(echo $CREDS | jq -r .Credentials.SecretAccessKey)" >> $GITHUB_ENV
        echo "AWS_SESSION_TOKEN=$(echo $CREDS | jq -r .Credentials.SessionToken)" >> $GITHUB_ENV

    - name: Sync build folder to S3
      run: |
        aws s3 sync collaborative-canvas/frontend/build/ s3://${{ secrets.S3_BUCKET_NAME }}/ --delete

    - name: Create CloudFront invalidation
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
          --paths "/*"
